package com.poly.java5.ai.service;

import com.poly.java5.ai.dto.ChatRequest;
import com.poly.java5.ai.dto.ChatResponse;
import com.poly.java5.ai.dto.ChatSourceDto;
import dev.langchain4j.data.document.Metadata;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.rag.content.Content;
import dev.langchain4j.service.Result;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.Optional;
import com.poly.java5.Repository.BookRepository;
import com.poly.java5.Entity.Book;
import com.poly.java5.Service.PromotionService;

@Service
public class ChatbotService {

    private static final Logger log = LoggerFactory.getLogger(ChatbotService.class);

    private final RagService ragService;
    private final ChatIntentService chatIntentService;
    private final BookRepository bookRepository;
    private final PromotionService promotionService;

    public ChatbotService(RagService ragService, ChatIntentService chatIntentService, BookRepository bookRepository, PromotionService promotionService) {
        this.ragService = ragService;
        this.chatIntentService = chatIntentService;
        this.bookRepository = bookRepository;
        this.promotionService = promotionService;
    }

    public ChatResponse handleChat(ChatRequest request, Integer userId) {
        String convId = request.getConversationId();
        if (convId == null || convId.isEmpty()) {
            convId = UUID.randomUUID().toString();
        }

        ChatIntentService.Intent intent = chatIntentService.detectIntent(request.getMessage());
        log.info("Detected intent: {}", intent);

        if (intent == ChatIntentService.Intent.OUT_OF_SCOPE) {
            return ChatResponse.builder()
                    .answer("Xin lỗi, tôi là trợ lý AI của nhà sách và chỉ có thể trả lời các câu hỏi liên quan đến sách, tác giả, đơn hàng và chính sách của nhà sách.")
                    .intent(intent.name())
                    .conversationId(convId)
                    .fallback(true)
                    .build();
        }

        try {
            Result<String> result = ragService.getAnswer(convId, request.getMessage(), userId);
            
            List<ChatSourceDto> sources = new ArrayList<>();
            if (result.sources() != null) {
                for (Content content : result.sources()) {
                    TextSegment segment = content.textSegment();
                    Metadata meta = segment.metadata();
                    if (meta.containsKey("bookId")) {
                        Integer bookId = meta.getInteger("bookId");
                        String title = meta.getString("title");
                        
                        // Prevent duplicates
                        boolean exists = sources.stream().anyMatch(s -> s.getBookId().equals(bookId));
                        if (!exists) {
                            Optional<Book> bookOpt = bookRepository.findById(bookId);
                            sources.add(ChatSourceDto.builder()
                                    .bookId(bookId)
                                    .title(title)
                                    .reason("Tìm thấy từ ngữ cảnh semantic") // Ideally generated by LLM, but hardcoded here for simplicity
                                    .imageUrl(bookOpt.map(Book::getImageUrl).orElse(null))
                                    .price(bookOpt.map(Book::getPrice).orElse(null))
                                    .stockQuantity(bookOpt.map(Book::getQuantity).orElse(null))
                                    .build());
                        }
                    }
                }
            }

            // Gợi ý sách khuyến mãi nếu hỏi về khuyến mãi / giá
            if (intent == ChatIntentService.Intent.PRICE_QUERY || request.getMessage().toLowerCase().contains("khuyến mãi")) {
                List<Book> promotedBooks = promotionService.getBooksForActivePromotions();
                // Duyệt ngược để khi add(0, ...) giữ đúng thứ tự
                for (int i = promotedBooks.size() - 1; i >= 0; i--) {
                    Book book = promotedBooks.get(i);
                    sources.removeIf(s -> s.getBookId().equals(book.getId()));
                    sources.add(0, ChatSourceDto.builder()
                            .bookId(book.getId())
                            .title(book.getTitle())
                            .reason("Sách đang được khuyến mãi")
                            .imageUrl(book.getImageUrl())
                            .price(book.getPrice())
                            .stockQuantity(book.getQuantity())
                            .build());
                }
            }

            String answerText = result.content();
            
            // Trích xuất ID sách từ câu trả lời của AI và đưa sách đó lên đầu danh sách sources
            java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("(?i)\\s*\\(ID:\\s*(\\d+)\\)");
            java.util.regex.Matcher matcher = pattern.matcher(answerText);
            while (matcher.find()) {
                try {
                    Integer bookId = Integer.parseInt(matcher.group(1));
                    
                    // Tìm và xóa bookId khỏi list hiện tại nếu có để đưa lên đầu
                    sources.removeIf(s -> s.getBookId().equals(bookId));
                    
                    bookRepository.findById(bookId).ifPresent(book -> {
                        sources.add(0, ChatSourceDto.builder()
                                .bookId(book.getId())
                                .title(book.getTitle())
                                .reason("Sách bạn đang quan tâm")
                                .imageUrl(book.getImageUrl())
                                .price(book.getPrice())
                                .stockQuantity(book.getQuantity())
                                .build());
                    });
                } catch (Exception ex) {
                    log.warn("Lỗi khi parse book ID từ AI", ex);
                }
            }
            // Làm sạch text hiển thị cho user
            answerText = answerText.replaceAll("(?i)\\s*\\(ID:\\s*\\d+\\)", "");

            return ChatResponse.builder()
                    .answer(answerText)
                    .intent(intent.name())
                    .sources(sources)
                    .conversationId(convId)
                    .fallback(false)
                    .build();
        } catch (Exception e) {
            log.error("AI Service Error", e);
            return ChatResponse.builder()
                    .answer("Hệ thống AI hiện tại đang quá tải hoặc gặp sự cố. Vui lòng thử lại sau.")
                    .intent(intent.name())
                    .conversationId(convId)
                    .fallback(true)
                    .build();
        }
    }
}
